// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

[assembly:System.Reflection.AssemblyVersionAttribute("4.0.1.0")]
[assembly:System.Diagnostics.DebuggableAttribute((System.Diagnostics.DebuggableAttribute.DebuggingModes)(2))]
[assembly:System.Reflection.AssemblyCompanyAttribute("Xamarin, Inc.")]
[assembly:System.Reflection.AssemblyCopyrightAttribute("Copyright (c) 2015 Xamarin Inc. (http://www.xamarin.com)")]
[assembly:System.Reflection.AssemblyDefaultAliasAttribute("System.Globalization.Calendars.dll")]
[assembly:System.Reflection.AssemblyDescriptionAttribute("System.Globalization.Calendars.dll")]
[assembly:System.Reflection.AssemblyFileVersionAttribute("4.0.0.0")]
[assembly:System.Reflection.AssemblyInformationalVersionAttribute("4.0.0.0")]
[assembly:System.Reflection.AssemblyProductAttribute("Mono Common Language Infrastructure")]
[assembly:System.Reflection.AssemblyTitleAttribute("System.Globalization.Calendars.dll")]
[assembly:System.Runtime.CompilerServices.CompilationRelaxationsAttribute(8)]
[assembly:System.Runtime.CompilerServices.RuntimeCompatibilityAttribute(WrapNonExceptionThrows=true)]
[assembly:System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(System.Globalization.ChineseLunisolarCalendar))]
[assembly:System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(System.Globalization.EastAsianLunisolarCalendar))]
[assembly:System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(System.Globalization.GregorianCalendar))]
[assembly:System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(System.Globalization.GregorianCalendarTypes))]
[assembly:System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(System.Globalization.HebrewCalendar))]
[assembly:System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(System.Globalization.HijriCalendar))]
[assembly:System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(System.Globalization.JapaneseCalendar))]
[assembly:System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(System.Globalization.JapaneseLunisolarCalendar))]
[assembly:System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(System.Globalization.JulianCalendar))]
[assembly:System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(System.Globalization.KoreanCalendar))]
[assembly:System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(System.Globalization.KoreanLunisolarCalendar))]
[assembly:System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(System.Globalization.PersianCalendar))]
[assembly:System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(System.Globalization.TaiwanCalendar))]
[assembly:System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(System.Globalization.TaiwanLunisolarCalendar))]
[assembly:System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(System.Globalization.ThaiBuddhistCalendar))]
[assembly:System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(System.Globalization.UmAlQuraCalendar))]
