// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

[assembly:System.Reflection.AssemblyVersionAttribute("4.0.0.0")]
[assembly:System.Diagnostics.DebuggableAttribute((System.Diagnostics.DebuggableAttribute.DebuggingModes)(2))]
[assembly:System.Reflection.AssemblyCompanyAttribute("Xamarin, Inc.")]
[assembly:System.Reflection.AssemblyCopyrightAttribute("Copyright (c) 2015 Xamarin Inc. (http://www.xamarin.com)")]
[assembly:System.Reflection.AssemblyDefaultAliasAttribute("System.IO.Pipes.dll")]
[assembly:System.Reflection.AssemblyDescriptionAttribute("System.IO.Pipes.dll")]
[assembly:System.Reflection.AssemblyFileVersionAttribute("4.0.0.0")]
[assembly:System.Reflection.AssemblyInformationalVersionAttribute("4.0.0.0")]
[assembly:System.Reflection.AssemblyProductAttribute("Mono Common Language Infrastructure")]
[assembly:System.Reflection.AssemblyTitleAttribute("System.IO.Pipes.dll")]
[assembly:System.Runtime.CompilerServices.CompilationRelaxationsAttribute(8)]
[assembly:System.Runtime.CompilerServices.RuntimeCompatibilityAttribute(WrapNonExceptionThrows=true)]
[assembly:System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Microsoft.Win32.SafeHandles.SafePipeHandle))]
[assembly:System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(System.IO.Pipes.AnonymousPipeClientStream))]
[assembly:System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(System.IO.Pipes.AnonymousPipeServerStream))]
[assembly:System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(System.IO.Pipes.NamedPipeClientStream))]
[assembly:System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(System.IO.Pipes.NamedPipeServerStream))]
[assembly:System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(System.IO.Pipes.PipeDirection))]
[assembly:System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(System.IO.Pipes.PipeOptions))]
[assembly:System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(System.IO.Pipes.PipeStream))]
[assembly:System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(System.IO.Pipes.PipeTransmissionMode))]
